In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('seaborn-whitegrid')
import warnings
warnings.filterwarnings('ignore')

C:\Users\User\AppData\Local\Temp\ipykernel_17716\279617451.py:4: MatplotlibDeprecationWarning: The seaborn styles shipped by Matplotlib are deprecated since 3.6, as they no longer correspond to the styles shipped by seaborn. However, they will remain available as 'seaborn-v0_8-<style>'. Alternatively, directly use the seaborn API instead.
  plt.style.use('seaborn-whitegrid')

In [2]:
df = pd.read_csv('outcomes.csv')
df

,date,Bz,Dp,X_GSM_r,Y_GSM_r,Z_GSM_r,R,r,theta,r_pred_hou,r_pinn,r_nn,r_nn_l1,r_nn_l2,r_nn_elastic,r_pinn_l1,r_pinn_l2,r_pinn_elastic,r_pred_shue
0,2010-11-12 19:22:48,-0.205,1.044208,10.90600,-1.721339,-3.244156,3.672541,11.507754,-0.156543,11.141021,11.177598,11.174067,11.309229,11.205471,11.222482,11.170865,11.149947,11.079306,11.344071
1,2005-07-20 05:35:12,-1.095,3.389163,-18.62000,21.996678,2.424830,22.129927,28.921239,2.273250,23.682809,26.840881,28.034628,28.438406,28.029856,27.828737,26.782320,26.876290,26.489548,26.846156
2,2008-10-21 22:39:18,0.370,1.245573,9.04582,-5.775553,2.352013,6.236103,10.987076,-0.568232,11.254581,11.341992,11.381269,11.338448,11.319122,11.418593,11.335733,11.316109,11.376917,11.565490
3,2011-01-18 17:48:13,0.095,1.746853,4.05437,-9.694075,-3.440757,10.286588,11.056754,-1.174672,12.363875,12.132503,11.762409,11.717506,11.653622,11.769243,12.033142,12.125560,12.121529,12.983579
4,2013-02-01 23:02:44,-3.745,1.445123,9.89783,-0.537842,-1.706693,1.789434,10.058286,-0.054286,10.470627,10.474977,10.519138,10.486456,10.305799,10.444116,10.362221,10.511388,10.286757,10.486207
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26152,2005-04-03 12:20:12,0.890,1.446474,9.53490,-5.154451,3.387496,6.167941,11.355959,-0.495588,10.885445,10.990851,11.116528,11.074664,11.070441,11.238894,11.093650,11.023538,11.106754,11.193927
26153,1998-12-19 18:16:48,-3.980,2.713297,7.40600,5.642004,-0.101618,5.642919,9.310820,0.651020,10.014780,10.291271,10.278148,10.464002,10.193707,10.185390,10.271072,9.997087,10.120527,10.159835
26154,2008-08-16 14:35:24,-2.460,1.957998,9.56286,-0.344548,3.083783,3.102971,10.053692,-0.036014,10.008639,10.002326,10.009109,10.177472,9.882764,9.994918,9.949089,10.090210,9.831868,10.141434
26155,2008-10-21 21:17:56,0.410,1.207279,8.81009,-6.600999,2.763627,7.156173,11.350264,-0.643024,11.443425,11.487496,11.479223,11.450283,11.433690,11.537478,11.468943,11.463756,11.519280,11.779719
26156,2009-11-12 11:03:05,-1.340,1.031815,9.00549,-8.623191,1.352110,8.728552,12.541390,-0.763715,11.968465,11.788351,11.494854,11.689183,11.588907,11.535974,11.693529,11.862344,11.697279,12.299266

In [3]:
df['theta_deg'] = np.degrees(df['theta'])
df

,date,Bz,Dp,X_GSM_r,Y_GSM_r,Z_GSM_r,R,r,theta,r_pred_hou,r_pinn,r_nn,r_nn_l1,r_nn_l2,r_nn_elastic,r_pinn_l1,r_pinn_l2,r_pinn_elastic,r_pred_shue,theta_deg
0,2010-11-12 19:22:48,-0.205,1.044208,10.90600,-1.721339,-3.244156,3.672541,11.507754,-0.156543,11.141021,11.177598,11.174067,11.309229,11.205471,11.222482,11.170865,11.149947,11.079306,11.344071,-8.969237
1,2005-07-20 05:35:12,-1.095,3.389163,-18.62000,21.996678,2.424830,22.129927,28.921239,2.273250,23.682809,26.840881,28.034628,28.438406,28.029856,27.828737,26.782320,26.876290,26.489548,26.846156,130.247629
2,2008-10-21 22:39:18,0.370,1.245573,9.04582,-5.775553,2.352013,6.236103,10.987076,-0.568232,11.254581,11.341992,11.381269,11.338448,11.319122,11.418593,11.335733,11.316109,11.376917,11.565490,-32.557317
3,2011-01-18 17:48:13,0.095,1.746853,4.05437,-9.694075,-3.440757,10.286588,11.056754,-1.174672,12.363875,12.132503,11.762409,11.717506,11.653622,11.769243,12.033142,12.125560,12.121529,12.983579,-67.303770
4,2013-02-01 23:02:44,-3.745,1.445123,9.89783,-0.537842,-1.706693,1.789434,10.058286,-0.054286,10.470627,10.474977,10.519138,10.486456,10.305799,10.444116,10.362221,10.511388,10.286757,10.486207,-3.110357
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26152,2005-04-03 12:20:12,0.890,1.446474,9.53490,-5.154451,3.387496,6.167941,11.355959,-0.495588,10.885445,10.990851,11.116528,11.074664,11.070441,11.238894,11.093650,11.023538,11.106754,11.193927,-28.395119
26153,1998-12-19 18:16:48,-3.980,2.713297,7.40600,5.642004,-0.101618,5.642919,9.310820,0.651020,10.014780,10.291271,10.278148,10.464002,10.193707,10.185390,10.271072,9.997087,10.120527,10.159835,37.300705
26154,2008-08-16 14:35:24,-2.460,1.957998,9.56286,-0.344548,3.083783,3.102971,10.053692,-0.036014,10.008639,10.002326,10.009109,10.177472,9.882764,9.994918,9.949089,10.090210,9.831868,10.141434,-2.063460
26155,2008-10-21 21:17:56,0.410,1.207279,8.81009,-6.600999,2.763627,7.156173,11.350264,-0.643024,11.443425,11.487496,11.479223,11.450283,11.433690,11.537478,11.468943,11.463756,11.519280,11.779719,-36.842547
26156,2009-11-12 11:03:05,-1.340,1.031815,9.00549,-8.623191,1.352110,8.728552,12.541390,-0.763715,11.968465,11.788351,11.494854,11.689183,11.588907,11.535974,11.693529,11.862344,11.697279,12.299266,-43.757667

# for abs(theta_deg) < 45

In [4]:
df_lt45 = df[abs(df['theta_deg']) < 45]
from sklearn.metrics import mean_squared_error
# calculate the RMSE for all r
print('RMSE of r_pred_shue: ', np.sqrt(mean_squared_error(df_lt45['r'], df_lt45['r_pred_shue'])))
print('RMSE of r_pred_hou: ', np.sqrt(mean_squared_error(df_lt45['r'], df_lt45['r_pred_hou'])))
print('RMSE of pinn_pred: ', np.sqrt(mean_squared_error(df_lt45['r'], df_lt45['r_pinn'])))
print('RMSE of nn_pred: ', np.sqrt(mean_squared_error(df_lt45['r'], df_lt45['r_nn'])))
print('RMSE of nn_l1_pred: ', np.sqrt(mean_squared_error(df_lt45['r'], df_lt45['r_nn_l1'])))
print('RMSE of nn_l2_pred: ', np.sqrt(mean_squared_error(df_lt45['r'], df_lt45['r_nn_l2'])))
print('RMSE of nn_elastic_pred: ', np.sqrt(mean_squared_error(df_lt45['r'], df_lt45['r_nn_elastic'])))
print('RMSE of pinn_l1_pred: ', np.sqrt(mean_squared_error(df_lt45['r'], df_lt45['r_pinn_l1'])))
print('RMSE of pinn_l2_pred: ', np.sqrt(mean_squared_error(df_lt45['r'], df_lt45['r_pinn_l2'])))
print('RMSE of pinn_elastic_pred: ', np.sqrt(mean_squared_error(df_lt45['r'], df_lt45['r_pinn_elastic'])))

RMSE of r_pred_shue:  0.709399548567585
RMSE of r_pred_hou:  0.7712773867613623
RMSE of pinn_pred:  0.7180590648388767
RMSE of nn_pred:  0.7232059477955551
RMSE of nn_l1_pred:  0.7043990073975294
RMSE of nn_l2_pred:  0.7317204819009281
RMSE of nn_elastic_pred:  0.7308236737938913
RMSE of pinn_l1_pred:  0.7114918281494108
RMSE of pinn_l2_pred:  0.7208554605488502
RMSE of pinn_elastic_pred:  0.7318192656060718

# for 120 > abs(theta_deg) > 45

In [5]:
df_45_120 = df[(abs(df['theta_deg']) >= 45) & (abs(df['theta_deg']) < 120)]
# calculate the RMSE for all r
print('RMSE of r_pred_shue: ', np.sqrt(mean_squared_error(df_45_120['r'], df_45_120['r_pred_shue'])))
print('RMSE of r_pred_hou: ', np.sqrt(mean_squared_error(df_45_120['r'], df_45_120['r_pred_hou'])))
print('RMSE of pinn_pred: ', np.sqrt(mean_squared_error(df_45_120['r'], df_45_120['r_pinn'])))
print('RMSE of nn_pred: ', np.sqrt(mean_squared_error(df_45_120['r'], df_45_120['r_nn'])))
print('RMSE of nn_l1_pred: ', np.sqrt(mean_squared_error(df_45_120['r'], df_45_120['r_nn_l1'])))
print('RMSE of nn_l2_pred: ', np.sqrt(mean_squared_error(df_45_120['r'], df_45_120['r_nn_l2'])))
print('RMSE of nn_elastic_pred: ', np.sqrt(mean_squared_error(df_45_120['r'], df_45_120['r_nn_elastic'])))
print('RMSE of pinn_l1_pred: ', np.sqrt(mean_squared_error(df_45_120['r'], df_45_120['r_pinn_l1'])))
print('RMSE of pinn_l2_pred: ', np.sqrt(mean_squared_error(df_45_120['r'], df_45_120['r_pinn_l2'])))
print('RMSE of pinn_elastic_pred: ', np.sqrt(mean_squared_error(df_45_120['r'], df_45_120['r_pinn_elastic'])))

RMSE of r_pred_shue:  1.2304018297160253
RMSE of r_pred_hou:  1.2106558241867218
RMSE of pinn_pred:  0.9861369020945003
RMSE of nn_pred:  1.0914347424724473
RMSE of nn_l1_pred:  1.0706424929221185
RMSE of nn_l2_pred:  1.1172674194769918
RMSE of nn_elastic_pred:  1.12318649515062
RMSE of pinn_l1_pred:  0.9771654636570656
RMSE of pinn_l2_pred:  1.0115768844190638
RMSE of pinn_elastic_pred:  1.0062102635180088

# for abs(theta_deg) > 120

In [6]:
df_gt120 = df[abs(df['theta_deg']) >= 120]

# calculate the RMSE for all r
print('RMSE of r_pred_shue: ', np.sqrt(mean_squared_error(df_gt120['r'], df_gt120['r_pred_shue'])))
print('RMSE of r_pred_hou: ', np.sqrt(mean_squared_error(df_gt120['r'], df_gt120['r_pred_hou'])))
print('RMSE of pinn_pred: ', np.sqrt(mean_squared_error(df_gt120['r'], df_gt120['r_pinn'])))
print('RMSE of nn_pred: ', np.sqrt(mean_squared_error(df_gt120['r'], df_gt120['r_nn'])))
print('RMSE of nn_l1_pred: ', np.sqrt(mean_squared_error(df_gt120['r'], df_gt120['r_nn_l1'])))
print('RMSE of nn_l2_pred: ', np.sqrt(mean_squared_error(df_gt120['r'], df_gt120['r_nn_l2'])))
print('RMSE of nn_elastic_pred: ', np.sqrt(mean_squared_error(df_gt120['r'], df_gt120['r_nn_elastic'])))
print('RMSE of pinn_l1_pred: ', np.sqrt(mean_squared_error(df_gt120['r'], df_gt120['r_pinn_l1'])))
print('RMSE of pinn_l2_pred: ', np.sqrt(mean_squared_error(df_gt120['r'], df_gt120['r_pinn_l2'])))

RMSE of r_pred_shue:  6.546159585935386
RMSE of r_pred_hou:  5.595809411662284
RMSE of pinn_pred:  2.751251190440696
RMSE of nn_pred:  3.172317048566806
RMSE of nn_l1_pred:  3.063465150004475
RMSE of nn_l2_pred:  3.0643123950495985
RMSE of nn_elastic_pred:  2.9813447368137442
RMSE of pinn_l1_pred:  2.670665876060363
RMSE of pinn_l2_pred:  2.7095517606832873